### ISSUE TITLE
Running is infuriatingly slow

### ISSUE THREAD

**Issue by Jared-Fogle** [ColonialMarines-Mirror/ColonialMarines-2018#44]

**Comment by CosmicScientist** [comment]
This is a problem with coming from /tg/station.

What slows you down:

- hunger
- damage
- armour
- wielding a weapon (holding one too?)
- weeds
- purple resin

tg speed would completely break the maps and roles in this game and render everyone incredibly bored by the timelocked barriers.


What would change if the muhrenes were sped up:

- all xenos can't catch them, unless sped up
- stationary queens die to blitzkrieg
- crushers can't reliably run over anyone
- static defences will never be made (not that tgstation players would want to)
- carrier traps can't be refilled after the greytide swarms in
- hivelords and drones can't build enough defences to match the moving battlefield or even ones that matter
- runners, lurkers and ravagers can't pounce anyone
- the entire defender branch sucks, until the instant stun praetorian appears
- the entire sentinel line, especially boiler, can't do anything
- everyone who complained about chasms complains about eggs

What would change if the xenos were sped up:

- nothing changes... for a third of the roster
- everyone cries due to tile based stuns
- everyone cries due to queen screeches out of nowhere
- no-one uses sniper rifles
- we begin a new era of yackety sax where ping and sprite perfect clicking prevails


A lot of the game would have to be gutted or changed to speed up everyone. So good luck you plucky coder who's reading this!

**Comment by CitrusGender** [comment]
code problem, go to the forums to suggest stuff.
https://tgstation13.org/phpBB/viewforum.php?f=65

We might change the movement speed though.
