### ISSUE TITLE
Fix not being able to reverse chest burst xenos

### ISSUE THREAD

**Issue by mrturkeytoe** [ColonialMarines-Mirror/ColonialMarines-2018#98]
A while back they made it so you can't interact with anything in your inventory while swallowed by a xeno, thereby making it impossible to get out of a clumsy xeno

**Comment by Rohesie** [comment]
They half-fixed it by the victim getting spewed up automatically after a certain time. Might require rebalancing.
Reverse chest burst is a bad feature, though. It simply means that instead of getting captured and infected, which gives you priority at taking control of the larva if you turn your xeno prefs on and stay in the body until you burst, you'll get killed and it's GG for you, wait until a xeno gets freed along with the rest of the ghosts.

**Comment by Rohesie** [comment]
You now get out of a xeno automatically at around 2 minutes if you are not inside a vent, unharmed.
